// <auto-generated />
namespace VidlyTwo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Agregar1233 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agregar1233));
        
        string IMigrationMetadata.Id
        {
            get { return "201810290356053_Agregar1233"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
