// <auto-generated />
namespace VidlyTwo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Archi_03_11_18_01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Archi_03_11_18_01));
        
        string IMigrationMetadata.Id
        {
            get { return "201811031722332_Archi_03_11_18_01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
